name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you experiencing this issue?
      options:
        - CLI
        - Web GUI
        - Both
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: Run `node --version` to find your Node.js version
      placeholder: "e.g., v20.10.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: "e.g., macOS 14.0, Windows 11, Ubuntu 22.04"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Run command `node index.js list -f calendar.ics`
        2. See error message
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Tell us what you expected
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Tell us what happened instead
    validations:
      required: true

  - type: textarea
    id: ics-sample
    attributes:
      label: Sample .ics File (Optional)
      description: If relevant, please provide a sample .ics file that reproduces the issue
      placeholder: Paste your .ics content here
      render: text

  - type: textarea
    id: logs
    attributes:
      label: Error Logs / Screenshots
      description: Please provide any error messages, stack traces, or screenshots
      placeholder: Paste logs or drag and drop screenshots here
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
